---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - test
    config:
      languages:
        javascript:
          mass_threshold: 100 # Defualt: 40
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- karma.conf.js
- webpack.config.js
- webpack.docs.config.js
- src/docs/langs.js
- docs/**/*.js
