root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
env:
  browser: true
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - ignoreRestSiblings: true
      argsIgnorePattern: '^_'
  '@typescript-eslint/no-explicit-any': 'error'
